#!/usr/bin/env bash
set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)"
UMBREL_ROOT="${APP_DATA_DIR}/../.."

CONFIG_PHP_FILE="${APP_DATA_DIR}/data/nextcloud/config/config.php"

APP_COMPOSE_FILE="${APP_DATA_DIR}/docker-compose.yml"
APP_COMPOSE_BACKUP_FILE="${APP_DATA_DIR}/docker-compose.yml.bak"

# Supported list of Nextcloud migrations
VERSIONS=()

IMAGES=()

find_index() {
	local -r value="${1}"
	shift
	local -r array=("$@")

	for i in "${!array[@]}"; do
		if [[ "${array[$i]}" == "${value}" ]]; then
			echo $i
			exit
		fi
	done

	echo -1
}

wait_for_value_in_file () {
	local -r file="${1}"
	local -r str="${2}"
	local -r max_seconds="${3}"

	echo "Searching for '${str}' inside: ${file}"

	for i in $(seq 1 "${max_seconds}"); do
		echo "Attempt: ${i}"
		if cat "${file}" | grep --quiet "${str}"; then
			return
		fi
		sleep 1
	done

	echo "Failed after ${max_seconds} seconds to find '${str}' inside: ${file}"
	exit 1
}

check_compose_file () {
	local -r image="${1}"

	web_image=$(cat "${APP_COMPOSE_FILE}" 2> /dev/null | yq '.services.web.image' || true)
	cron_image=$(cat "${APP_COMPOSE_FILE}" 2> /dev/null | yq '.services.cron.image' || true)

	if [[ "${web_image}" != "${image}" ]] || [[ "${cron_image}" != "${image}" ]]; then
		echo "The docker-compose.yml now looks bad. Restoring..."

		mv "${APP_COMPOSE_BACKUP_FILE}" "${APP_COMPOSE_FILE}"

		exit
	fi
}

get_version() {
	cat "${CONFIG_PHP_FILE}" | grep "'version'[[:space:]]=>[[:space:]]" | awk -F"'" '{print $4}'
}

# If a Nextcloud config file does not yet exist
# Then it's likely a new install
# Therefore there is nothing to do
if [[ ! -f "${CONFIG_PHP_FILE}" ]]; then
	exit
fi

nextcloud_version=$(get_version)

echo "Active Nextcloud Version: ${nextcloud_version}"

# Check if active version is in migration list
active_version_idx=$(find_index "${nextcloud_version}" "${VERSIONS[@]}")
if [[ "${active_version_idx}" == "-1" ]]; then
	echo "Active version is not supported in the list of migrations"
	exit
fi

# Check if already up to date
if [[ "${VERSIONS[-1]}" == "${nextcloud_version}" ]]; then
	echo "Nextcloud is up-to-date"
	exit
fi

# Loop through versions, ignoring past versions
for i in "${!VERSIONS[@]}"; do
	[[ "${i}" -le "${active_version_idx}" ]] && continue

	version="${VERSIONS[$i]}"
	image="${IMAGES[$i]}"

	echo "Migrating to: ${version} (${image})"
	echo

	cp --archive "${APP_COMPOSE_FILE}" "${APP_COMPOSE_BACKUP_FILE}"

	yq -i ".services.web.image = \"${image}\"" "${APP_COMPOSE_FILE}"
	yq -i ".services.cron.image = \"${image}\"" "${APP_COMPOSE_FILE}"

	check_compose_file "${image}"

	nextcloud_version=$(get_version)
	sed -i "s/${nextcloud_version}/${nextcloud_version}-patch/" "${CONFIG_PHP_FILE}"

	"${UMBREL_ROOT}/scripts/app" start nextcloud

	echo "Waiting for update to complete..."

	# Wait for Nextcloud to enter maintenance mode
	# Indicating their update process has started
	wait_for_value_in_file "${CONFIG_PHP_FILE}" "'maintenance'[[:space:]]=>[[:space:]]true" 300

	# Wait for Nextcloud to exit maintenance mode
	# Indicating their update process has finished
	wait_for_value_in_file "${CONFIG_PHP_FILE}" "'maintenance'[[:space:]]=>[[:space:]]false" 300

	"${UMBREL_ROOT}/scripts/app" stop nextcloud

	# Delete image of intermediate version
	# Unless it's the latest image
	# Otherwise it will have to be re-downloaded
	if [[ "${version}" != "${VERSIONS[-1]}" ]]; then
		echo "Deleting intermediary image: ${image}"

		docker rmi "${image}" || true
	fi
done

rm -rf "${APP_COMPOSE_BACKUP_FILE}"

echo "Migration completed successfully"
